### PR TITLE
Replace initial state of queryResult from null to proper object structure

### PR DESCRIPTION
**Pull request by bsubedi26**
PR to fix issue: https://github.com/feathers-plus/feathers-redux/issues/42

### CODE REVIEW

**Comment by eddyystop** [comment]
I'll wait for this discussion to finish before merging.

**Comment by bsubedi26** [comment]
@erkkaha:  `state[opts.queryResult]` within PENDING, FULFILLED and REJECTED reducers are basically essentially the same data structure as `queryResultDefaults` because of the initial state for queryResult.

Are you referring to removing the null within PENDING, FULFILLED and REJECTED reducers like this?
```
[opts.queryResult]: state[opts.queryResult] || queryResultDefaults
```

**Comment by erkkaha** [comment]
@bsubedi26 With removing nulls I was thinking taking the ```|| null``` completely away, since queryResult should now always exist?

**Comment by bsubedi26** [comment]
@erkkaha That definitely makes sense. Unfortunately, removing ```|| null``` breaks some of the old tests (which I did not write).

**Comment by erkkaha** [comment]
@bsubedi26 @eddyystop Maybe this can be merged and I can do a separate PR for removing those nulls.

**Comment by eddyystop** [comment]
Published as 2.1.0

**Comment by eddyystop** [comment]
@erkkaha Let me know if you will be looking into removing the nulls.

**Pull request merged**
